import { SymbolDatabase, OntologyField } from '../types';

export const ONTOLOGY_FIELDS: OntologyField[] = [
  {
    name: "Formal & Mathematical Foundations",
    description: "Logic, mathematics, set theory, complexity theory, and optimization.",
    domains: ["Logic", "Mathematics", "Set_Theory", "Measure_Theory", "Complexity_Theory", "Comp_Learning", "Uncertainty_Probability", "Diff_Geometry", "Optimization"]
  },
  {
    name: "Temporal & Causal Foundations",
    description: "Time, causality, and inference.",
    domains: ["Time_Temporality", "Causality", "Causal_Inference"]
  },
  {
    name: "Physical Sciences & Engineering",
    description: "Physics, chemistry, materials, and fluid dynamics.",
    domains: ["Physics", "Chemistry", "Materials_Science", "Fluid_Dynamics", "General_Relativity"]
  },
  {
    name: "Scientific & Technical Systems",
    description: "Information, networks, control, computer science, and dynamical systems.",
    domains: ["Systems_Theory", "Info_Theory", "Network_Theory", "Control_Theory", "Dynamical_Systems", "Stochastic", "Signal_Processing", "Cryptography", "Computer_Science"]
  },
  {
    name: "Biological & Life Sciences",
    description: "Evolution, neuroscience, medicine, and ecology.",
    domains: ["Biology", "Evolutionary_Biology", "Neuroscience", "Medicine_Health", "Pharmacology", "Epidemiology", "Ecology"]
  },
  {
    name: "Cognitive & Psychological",
    description: "Mind, consciousness, linguistics, and wisdom.",
    domains: ["Cognition", "Consciousness", "Philosophy_of_Mind", "Linguistics", "Wisdom"]
  },
  {
    name: "Social & Political Systems",
    description: "Economics, law, ethics, political science, and decision theory.",
    domains: ["Social_Dynamics", "Economics", "Social_Choice", "Law", "Ethics", "Political_Science", "Decision_Theory", "Game_Theory"]
  },
  {
    name: "Applied & Practical Domains",
    description: "Physical artifacts, industries, and practical contexts.",
    domains: ["Environmental", "AI_Tech", "Emergency_Response", "Transport_Mobility", "Footwear", "Sports_Equipment", "Clothing_Textiles", "Color_Spectrum", "Art_Aesthetics"]
  }
];

export const LIBRARY: SymbolDatabase = {
  ontology_fields: ONTOLOGY_FIELDS,
  symbols: [
    // TOTAL GLYPH COUNT: 197 (V9.1 Refined Codex)
    // INVARIANT_KERNEL & FOUNDATIONAL
    { glyph: "⚓", meaning: "Stability Anchor", domain: "Computer_Science", weight: 100, opposites: [] },
    { glyph: "🐋", meaning: "Eternal Protocol", domain: "Computer_Science", weight: 100, opposites: ["💀"] },
    { glyph: "⛓️", meaning: "Standard Chain", domain: "Computer_Science", weight: 80, opposites: [] },
    { glyph: "💀", meaning: "Bravery Sacrifice", domain: "Emergency_Response", weight: 80, opposites: ["🐋"] },
    { glyph: "🕯️", meaning: "Light/Awareness", domain: "Wisdom", weight: 100, opposites: ["🕳️"] },
    { glyph: "🕳️", meaning: "The Void", domain: "Logic", weight: 0, opposites: ["🕯️"] },
    { glyph: "🌪️", meaning: "Chaos-to-Clarity", domain: "Environmental", weight: 80, opposites: ["🧘"] },
    { glyph: "🧘", meaning: "Listening Posture", domain: "Wisdom", weight: 60, opposites: ["🌪️"] },
    { glyph: "🦁", meaning: "Lion at the Helm", domain: "Social_Dynamics", weight: 80, opposites: [] },
    { glyph: "🌿", meaning: "Growth", domain: "Environmental", weight: 60, opposites: [] },
    { glyph: "🎯", meaning: "Precision Target", domain: "AI_Tech", weight: 80, opposites: [] },
    
    // TIME_TEMPORALITY
    { glyph: "⏳", meaning: "Entropy Time Arrow", domain: "Time_Temporality", weight: 60, opposites: ["⌛"] },
    { glyph: "⌛", meaning: "Psychological Duration", domain: "Time_Temporality", weight: 60, opposites: ["⏳"] },
    { glyph: "⏰", meaning: "Synchronization", domain: "Time_Temporality", weight: 40, opposites: [] },
    { glyph: "⏱️", meaning: "Precise Measurement", domain: "Time_Temporality", weight: 40, opposites: [] },
    { glyph: "⚡", meaning: "Instant Moment", domain: "Time_Temporality", weight: 100, opposites: [] },
    { glyph: "🌅", meaning: "Dawn Beginning", domain: "Time_Temporality", weight: 80, opposites: ["🌇"] },
    { glyph: "🌇", meaning: "Dusk Ending", domain: "Time_Temporality", weight: 80, opposites: ["🌅"] },
    { glyph: "🌊", meaning: "Flow Duration", domain: "Time_Temporality", weight: 60, opposites: [] },

    // UNCERTAINTY & PROBABILITY
    { glyph: "🎲", meaning: "Random Variable", domain: "Uncertainty_Probability", weight: 40, opposites: ["🎯"] },
    { glyph: "📊", meaning: "Probability Distribution", domain: "Uncertainty_Probability", weight: 60, opposites: [] },
    { glyph: "🔮", meaning: "Predictive Interval", domain: "Uncertainty_Probability", weight: 80, opposites: [] },
    { glyph: "📈", meaning: "Expected Value", domain: "Uncertainty_Probability", weight: 60, opposites: ["📉"] },
    { glyph: "📉", meaning: "Variance", domain: "Uncertainty_Probability", weight: 60, opposites: ["📈"] },
    { glyph: "🌀", meaning: "Entropy Uncertainty", domain: "Uncertainty_Probability", weight: 40, opposites: [] },

    // SPACE & GEOMETRY
    { glyph: "📏", meaning: "Metric Distance", domain: "Mathematics", weight: 40, opposites: [] },
    { glyph: "🌐", meaning: "Topological Connectivity", domain: "Mathematics", weight: 80, opposites: [] },
    { glyph: "🕸️", meaning: "Manifold Structure", domain: "Mathematics", weight: 80, opposites: [] },
    { glyph: "📐", meaning: "Geometric Form", domain: "Mathematics", weight: 60, opposites: [] },
    { glyph: "🔼", meaning: "Dimensionality", domain: "Mathematics", weight: 80, opposites: [] },
    { glyph: "🌌", meaning: "Spatial Infinity", domain: "Physics", weight: 100, opposites: [] },

    // CONSCIOUSNESS
    { glyph: "👁️", meaning: "The Witness / Observer", domain: "Consciousness", weight: 100, opposites: [] },
    { glyph: "🧠", meaning: "Consciousness Operator", domain: "Consciousness", weight: 100, opposites: [] },
    { glyph: "🌟", meaning: "Significance Gradient", domain: "Consciousness", weight: 80, opposites: [] },
    { glyph: "👥", meaning: "Shadow Processing", domain: "Consciousness", weight: 60, opposites: [] },
    { glyph: "🏛️", meaning: "Cultural Current", domain: "Consciousness", weight: 80, opposites: [] },
    { glyph: "💭", meaning: "Meaning Flow", domain: "Consciousness", weight: 60, opposites: [] },
    { glyph: "🎭", meaning: "Persona Mask", domain: "Consciousness", weight: 40, opposites: [] },

    // CAUSALITY & LOGIC
    { glyph: "➡️", meaning: "Direct Causation", domain: "Causality", weight: 40, opposites: [] },
    { glyph: "⚖️", meaning: "Causal Strength / Balance", domain: "Causality", weight: 80, opposites: [] },
    { glyph: "🔄", meaning: "Feedback Loop", domain: "Causality", weight: 60, opposites: [] },
    { glyph: "∧", meaning: "And Conjunction", domain: "Logic", weight: 40, opposites: ["∨"] },
    { glyph: "∨", meaning: "Or Disjunction", domain: "Logic", weight: 40, opposites: ["∧"] },
    { glyph: "¬", meaning: "Not Negation", domain: "Logic", weight: 60, opposites: [] },
    { glyph: "∀", meaning: "Universal Quantification", domain: "Logic", weight: 80, opposites: ["∃"] },
    { glyph: "∃", meaning: "Existential Quantification", domain: "Logic", weight: 80, opposites: ["∀"] },
    { glyph: "⊢", meaning: "Provable Derivation", domain: "Logic", weight: 100, opposites: [] },
    { glyph: "⊨", meaning: "Semantic Entailment", domain: "Logic", weight: 100, opposites: [] },
    { glyph: "⊥", meaning: "Contradiction", domain: "Logic", weight: 0, opposites: ["⊤"] },
    { glyph: "⊤", meaning: "Tautology", domain: "Logic", weight: 100, opposites: ["⊥"] },
    
    // MATHEMATICS
    { glyph: "✔", meaning: "Universality", domain: "Mathematics", weight: 100, opposites: [] },
    { glyph: "≡", meaning: "Identity", domain: "Mathematics", weight: 100, opposites: ["≠"] },
    { glyph: "≠", meaning: "Distinction", domain: "Mathematics", weight: 60, opposites: ["≡"] },
    { glyph: "⊗", meaning: "Composition", domain: "Mathematics", weight: 80, opposites: [] },
    { glyph: "∅", meaning: "Empty Set", domain: "Mathematics", weight: 0, opposites: ["✔"] },
    { glyph: "∞", meaning: "Infinity", domain: "Mathematics", weight: 100, opposites: [] },
    
    // SYSTEMS & INFO THEORY
    { glyph: "🎛️", meaning: "Control Input", domain: "Systems_Theory", weight: 60, opposites: [] },
    { glyph: "🔴", meaning: "Damping Resistance", domain: "Systems_Theory", weight: 40, opposites: ["📢"] },
    { glyph: "📢", meaning: "Amplification Gain", domain: "Systems_Theory", weight: 80, opposites: ["🔴"] },
    { glyph: "🧲", meaning: "Attractor Basin", domain: "Systems_Theory", weight: 80, opposites: [] },
    { glyph: "🏗️", meaning: "Emergent Structure", domain: "Systems_Theory", weight: 100, opposites: [] },
    { glyph: "⚙️", meaning: "Machine Architecture", domain: "Computer_Science", weight: 60, opposites: [] },
    { glyph: "★", meaning: "Compression Efficiency", domain: "Info_Theory", weight: 80, opposites: [] },
    
    // PHYSICS & CHEMISTRY
    { glyph: "💎", meaning: "Particle", domain: "Physics", weight: 40, opposites: ["🌊"] },
    { glyph: "❄️", meaning: "Endothermic", domain: "Chemistry", weight: 60, opposites: ["🔥"] },
    
    // BIOLOGY & MEDICINE
    { glyph: "🧬", meaning: "DNA Sequence", domain: "Biology", weight: 100, opposites: [] },
    { glyph: "⚠️", meaning: "Risk Factor / Warning", domain: "Emergency_Response", weight: 40, opposites: [] },
    { glyph: "❤️", meaning: "Cardiac Health / Vitality", domain: "Medicine_Health", weight: 100, opposites: [] },
    { glyph: "🏥", meaning: "Medical Facility", domain: "Medicine_Health", weight: 80, opposites: [] },
    
    // SOCIAL & ECONOMICS
    { glyph: "🗣️", meaning: "Communication Loop", domain: "Social_Dynamics", weight: 60, opposites: [] },
    { glyph: "🚀", meaning: "Social Momentum", domain: "Social_Dynamics", weight: 80, opposites: ["🛑"] },
    { glyph: "🛑", meaning: "Social Inertia", domain: "Social_Dynamics", weight: 40, opposites: ["🚀"] },
    { glyph: "💥", meaning: "Social Conflict", domain: "Social_Dynamics", weight: 20, opposites: ["🤝"] },
    { glyph: "🤝", meaning: "Cooperation", domain: "Social_Dynamics", weight: 80, opposites: ["💥"] },
    { glyph: "🏆", meaning: "Optimal Outcome", domain: "Economics", weight: 100, opposites: [] },
    { glyph: "💰", meaning: "Cost Expense", domain: "Economics", weight: 40, opposites: ["📈"] },

    // NAVIGATION & TRANSPORT
    { glyph: "🆘", meaning: "Emergency Distress", domain: "Emergency_Response", weight: 20, opposites: [] },
    { glyph: "🚩", meaning: "Crisis Flag", domain: "Emergency_Response", weight: 40, opposites: [] },
    { glyph: "🚨", meaning: "Escalation Signal", domain: "Emergency_Response", weight: 60, opposites: [] },
    { glyph: "🔒", meaning: "Containment Isolation", domain: "Emergency_Response", weight: 80, opposites: [] },
    { glyph: "🛣️", meaning: "Route Pathway", domain: "Transport_Mobility", weight: 60, opposites: [] },
    { glyph: "📍", meaning: "Waypoint Milestone", domain: "Transport_Mobility", weight: 40, opposites: [] },

    // ENVIRONMENTAL
    { glyph: "🌍", meaning: "Planet Earth", domain: "Environmental", weight: 100, opposites: [] },
    { glyph: "💧", meaning: "Water Hydrology", domain: "Environmental", weight: 80, opposites: ["🔥"] },
    { glyph: "☁️", meaning: "Air Atmosphere", domain: "Environmental", weight: 60, opposites: [] },
    { glyph: "🪨", meaning: "Earth Geology", domain: "Environmental", weight: 60, opposites: [] },
    { glyph: "🛡️", meaning: "Conservation Protection", domain: "Environmental", weight: 80, opposites: [] },

    // MUSIC & ARTS
    { glyph: "🎶", meaning: "Motif Theme", domain: "Art_Aesthetics", weight: 60, opposites: [] },
    { glyph: "🎵", meaning: "Tempo Pacing", domain: "Art_Aesthetics", weight: 40, opposites: [] },
    { glyph: "🎼", meaning: "Harmony Chord", domain: "Art_Aesthetics", weight: 80, opposites: [] },
    { glyph: "🥁", meaning: "Rhythm Pattern", domain: "Art_Aesthetics", weight: 60, opposites: [] },
    { glyph: "💓", meaning: "Affective Resonance", domain: "Art_Aesthetics", weight: 100, opposites: [] },
    { glyph: "🎧", meaning: "Listening Reception", domain: "Art_Aesthetics", weight: 40, opposites: [] },

    // WISDOM & ETHICS
    { glyph: "⚔️", meaning: "Courage Blade", domain: "Wisdom", weight: 80, opposites: [] },
    { glyph: "✅", meaning: "Permitted Allowed", domain: "Ethics", weight: 60, opposites: ["❌"] },
    { glyph: "➕", meaning: "Recursive Loop", domain: "Consciousness", weight: 60, opposites: [] },
    { glyph: "◆", meaning: "Salience Prominence", domain: "Cognition", weight: 60, opposites: [] },
    { glyph: "🔥", meaning: "Abandonment Flame", domain: "Wisdom", weight: 80, opposites: [] },
    { glyph: "🧹", meaning: "Elegance Sweeper", domain: "Wisdom", weight: 60, opposites: [] },
    { glyph: "🧭", meaning: "Falsification Compass", domain: "Wisdom", weight: 80, opposites: [] },

    // LINGUISTICS & SEMANTICS
    { glyph: "λ", meaning: "Lambda Abstraction", domain: "Linguistics", weight: 80, opposites: [] },
    { glyph: "θ", meaning: "Theta Role", domain: "Linguistics", weight: 60, opposites: [] },
    { glyph: "φ", meaning: "Phi Features", domain: "Linguistics", weight: 60, opposites: [] },
    { glyph: "Σ", meaning: "Lexicon Set", domain: "Linguistics", weight: 80, opposites: [] },

    // COSMOLOGY & PHYSICS
    { glyph: "Λ", meaning: "Cosmological Constant", domain: "Physics", weight: 100, opposites: [] },
    { glyph: "Ω", meaning: "Density Parameter", domain: "Physics", weight: 80, opposites: [] },
    { glyph: "H", meaning: "Hubble Parameter", domain: "Physics", weight: 80, opposites: [] },

    // PARTICLE PHYSICS
    { glyph: "γ", meaning: "Photon", domain: "Physics", weight: 100, opposites: [] },
    { glyph: "ν", meaning: "Neutrino", domain: "Physics", weight: 60, opposites: [] },
    { glyph: "μ", meaning: "Muon", domain: "Physics", weight: 60, opposites: [] },
    { glyph: "τ", meaning: "Tau", domain: "Physics", weight: 60, opposites: [] },
    { glyph: "π", meaning: "Pion", domain: "Physics", weight: 60, opposites: [] },

    // PHILOSOPHY & LOGIC
    { glyph: "◇", meaning: "Possible Contingent", domain: "Logic", weight: 60, opposites: ["□"] },
    { glyph: "□", meaning: "Necessary Inevitable", domain: "Logic", weight: 100, opposites: ["◇"] },
    
    // V9 RESEARCH UPGRADE SYMBOLS
    { glyph: "do(·)", meaning: "Causal Intervention", domain: "Causal_Inference", weight: 100, opposites: [] },
    { glyph: "∇", meaning: "Gradient Operator", domain: "Mathematics", weight: 80, opposites: [] },
    { glyph: "💝", meaning: "Integrated Compassion", domain: "Wisdom", weight: 100, opposites: [] },
    { glyph: "🧵", meaning: "Textile Thread", domain: "Clothing_Textiles", weight: 60, opposites: [] },
    { glyph: "🚗", meaning: "Automotive Mobility", domain: "Transport_Mobility", weight: 60, opposites: [] },
    { glyph: "👟", meaning: "Athletic Footwear", domain: "Footwear", weight: 40, opposites: [] },
    { glyph: "👢", meaning: "Industrial Protection", domain: "Footwear", weight: 40, opposites: [] },
    { glyph: "🏋️", meaning: "Physical Training", domain: "Sports_Equipment", weight: 60, opposites: [] },
    { glyph: "🌈", meaning: "Chromatic Spectrum", domain: "Color_Spectrum", weight: 80, opposites: [] },
    { glyph: "ẋ", meaning: "Time Derivative", domain: "Dynamical_Systems", weight: 60, opposites: [] },
    { glyph: "⇄", meaning: "Ecological Exchange", domain: "Ecology", weight: 60, opposites: [] },
    { glyph: "∇J", meaning: "Loss Gradient", domain: "Optimization", weight: 80, opposites: [] },
    { glyph: "NE", meaning: "Nash Equilibrium", domain: "Game_Theory", weight: 100, opposites: [] },
    { glyph: "VCG", meaning: "Mechanism Design", domain: "Game_Theory", weight: 100, opposites: [] },
    { glyph: "LTP", meaning: "Long-Term Potentiation", domain: "Neuroscience", weight: 80, opposites: [] },
    { glyph: "SNR", meaning: "Signal-to-Noise Ratio", domain: "Signal_Processing", weight: 60, opposites: [] },
    { glyph: "G_s", meaning: "Transfer Function", domain: "Control_Theory", weight: 80, opposites: [] },
    { glyph: "ZKP", meaning: "Zero-Knowledge Proof", domain: "Cryptography", weight: 100, opposites: [] },
    { glyph: "E_X", meaning: "Expected Value Operator", domain: "Stochastic", weight: 60, opposites: [] },
    { glyph: "w_fit", meaning: "Biological Fitness", domain: "Evolutionary_Biology", weight: 100, opposites: [] },
    { glyph: "int_mu", meaning: "Lebesgue Integral", domain: "Measure_Theory", weight: 100, opposites: [] },
    { glyph: "Ric", meaning: "Ricci Curvature", domain: "Diff_Geometry", weight: 100, opposites: [] },
    { glyph: "NP_c", meaning: "NP-Completeness", domain: "Complexity_Theory", weight: 100, opposites: [] },
    { glyph: "PAC", meaning: "Probably Approximately Correct", domain: "Comp_Learning", weight: 100, opposites: [] },
    { glyph: "R₀", meaning: "Basic Reproduction Number", domain: "Epidemiology", weight: 100, opposites: [] },
    { glyph: "EC50", meaning: "Half Maximal Effective Conc", domain: "Pharmacology", weight: 80, opposites: [] },
    { glyph: "qualia", meaning: "Subjective Experience", domain: "Philosophy_of_Mind", weight: 100, opposites: [] },
    { glyph: "ATE", meaning: "Average Treatment Effect", domain: "Causal_Inference", weight: 80, opposites: [] },
    { glyph: "EU", meaning: "Expected Utility", domain: "Decision_Theory", weight: 100, opposites: [] },
    { glyph: "stare", meaning: "Legal Precedent", domain: "Law", weight: 80, opposites: [] },
    { glyph: "⟦·⟧", meaning: "Semantic Interpretation", domain: "Linguistics", weight: 80, opposites: [] },
    { glyph: "E_Y", meaning: "Young's Modulus", domain: "Materials_Science", weight: 80, opposites: [] },
    { glyph: "Re", meaning: "Reynolds Number", domain: "Fluid_Dynamics", weight: 80, opposites: [] },
    { glyph: "Ma", meaning: "Mach Number", domain: "Fluid_Dynamics", weight: 80, opposites: [] },
    { glyph: "St", meaning: "Strouhal Number", domain: "Fluid_Dynamics", weight: 60, opposites: [] },
    
    // NEW V9.1 ADDITIONS
    { glyph: "∪", meaning: "Set Union", domain: "Set_Theory", weight: 60, opposites: ["∩"] },
    { glyph: "∩", meaning: "Set Intersection", domain: "Set_Theory", weight: 60, opposites: ["∪"] },
    { glyph: "⊂", meaning: "Proper Subset", domain: "Set_Theory", weight: 40, opposites: [] },
    { glyph: "ℵ₀", meaning: "Countable Infinity", domain: "Set_Theory", weight: 100, opposites: [] },
    { glyph: "μ_m", meaning: "Measure Function", domain: "Measure_Theory", weight: 80, opposites: [] },
    { glyph: "σ-alg", meaning: "Sigma Algebra", domain: "Measure_Theory", weight: 80, opposites: [] },
    { glyph: "P", meaning: "Polynomial Time", domain: "Complexity_Theory", weight: 100, opposites: ["NP"] },
    { glyph: "NP", meaning: "Non-deterministic Poly", domain: "Complexity_Theory", weight: 100, opposites: ["P"] },
    { glyph: "VC", meaning: "VC Dimension", domain: "Comp_Learning", weight: 80, opposites: [] },
    { glyph: "ERM", meaning: "Empirical Risk Min", domain: "Comp_Learning", weight: 80, opposites: [] },
    { glyph: "U(x)", meaning: "Utility Function", domain: "Decision_Theory", weight: 80, opposites: [] },
    { glyph: "π_pol", meaning: "Decision Policy", domain: "Decision_Theory", weight: 80, opposites: [] },
    { glyph: "λ_lag", meaning: "Lagrange Multiplier", domain: "Optimization", weight: 80, opposites: [] },
    { glyph: "KKT", meaning: "KKT Conditions", domain: "Optimization", weight: 100, opposites: [] },
    { glyph: "BR", meaning: "Best Response", domain: "Game_Theory", weight: 80, opposites: [] },
    { glyph: "PoA", meaning: "Price of Anarchy", domain: "Game_Theory", weight: 80, opposites: [] },
    { glyph: "k_deg", meaning: "Node Degree", domain: "Network_Theory", weight: 60, opposites: [] },
    { glyph: "C_clus", meaning: "Clustering Coeff", domain: "Network_Theory", weight: 60, opposites: [] },
    { glyph: "u(t)", meaning: "Control Signal", domain: "Control_Theory", weight: 80, opposites: [] },
    { glyph: "y(t)", meaning: "System Output", domain: "Control_Theory", weight: 80, opposites: [] },
    { glyph: "φ_flow", meaning: "System Flow", domain: "Dynamical_Systems", weight: 80, opposites: [] },
    { glyph: "x*", meaning: "Fixed Point", domain: "Dynamical_Systems", weight: 100, opposites: [] },
    { glyph: "W_t", meaning: "Wiener Process", domain: "Stochastic", weight: 80, opposites: [] },
    { glyph: "M_t", meaning: "Martingale", domain: "Stochastic", weight: 80, opposites: [] },
    { glyph: "FFT", meaning: "Fourier Transform", domain: "Signal_Processing", weight: 100, opposites: [] },
    { glyph: "H(z)", meaning: "Z-Transform", domain: "Signal_Processing", weight: 80, opposites: [] },
    { glyph: "Enc", meaning: "Encryption", domain: "Cryptography", weight: 80, opposites: ["Dec"] },
    { glyph: "Dec", meaning: "Decryption", domain: "Cryptography", weight: 80, opposites: ["Enc"] },
    { glyph: "σ_str", meaning: "Material Stress", domain: "Materials_Science", weight: 80, opposites: [] },
    { glyph: "ε_str", meaning: "Material Strain", domain: "Materials_Science", weight: 80, opposites: [] },
    { glyph: "s_sel", meaning: "Selection Coeff", domain: "Evolutionary_Biology", weight: 80, opposites: [] },
    { glyph: "μ_mut", meaning: "Mutation Rate", domain: "Evolutionary_Biology", weight: 60, opposites: [] },
    { glyph: "fMRI", meaning: "Neural Imaging", domain: "Neuroscience", weight: 80, opposites: [] },
    { glyph: "IC50", meaning: "Inhibitory Conc", domain: "Pharmacology", weight: 80, opposites: [] },
    { glyph: "SIR", meaning: "Epidemic Model", domain: "Epidemiology", weight: 100, opposites: [] },
    { glyph: "K_cap", meaning: "Carrying Capacity", domain: "Ecology", weight: 80, opposites: [] },
    { glyph: "intent", meaning: "Intentionality", domain: "Philosophy_of_Mind", weight: 80, opposites: [] },
    { glyph: "Borda", meaning: "Borda Count", domain: "Social_Choice", weight: 80, opposites: [] },
    { glyph: "lex", meaning: "Legal Code", domain: "Law", weight: 80, opposites: [] },
    { glyph: "sole", meaning: "Footwear Base", domain: "Footwear", weight: 40, opposites: [] },
    { glyph: "ball", meaning: "Sporting Sphere", domain: "Sports_Equipment", weight: 40, opposites: [] },
    { glyph: "weave", meaning: "Textile Pattern", domain: "Clothing_Textiles", weight: 60, opposites: [] },
    { glyph: "hue", meaning: "Color Identity", domain: "Color_Spectrum", weight: 60, opposites: [] },
    { glyph: "DAG", meaning: "Causal Graph", domain: "Causal_Inference", weight: 100, opposites: [] },
    { glyph: "demos", meaning: "The People", domain: "Political_Science", weight: 100, opposites: [] },
    { glyph: "g_uv", meaning: "Metric Tensor", domain: "Diff_Geometry", weight: 100, opposites: [] },
    { glyph: "Γ_ijk", meaning: "Christoffel Symbol", domain: "Diff_Geometry", weight: 80, opposites: [] },
    // BRIDGING THE GAP: Missing Symbols from V9 Spec
    { glyph: "g", meaning: "Gravitational Acceleration", domain: "General_Relativity", weight: 60, opposites: [] },
    { glyph: "Γ", meaning: "Affine Connection", domain: "General_Relativity", weight: 80, opposites: [] },
    { glyph: "R", meaning: "Ricci Scalar", domain: "General_Relativity", weight: 100, opposites: [] },
    { glyph: "G", meaning: "Einstein Tensor", domain: "General_Relativity", weight: 100, opposites: [] },
    { glyph: "T", meaning: "Stress-Energy Tensor", domain: "General_Relativity", weight: 100, opposites: [] },
    { glyph: "🔇", meaning: "Silence / Damping", domain: "Emergency_Response", weight: 40, opposites: ["📢"] },
    { glyph: "🔗", meaning: "Network Link", domain: "Social_Dynamics", weight: 60, opposites: [] },
    { glyph: "💡", meaning: "Innovation Insight", domain: "Economics", weight: 80, opposites: [] },
    { glyph: "🔁", meaning: "Iterative Loop", domain: "Art_Aesthetics", weight: 40, opposites: [] },
    { glyph: "🎷", meaning: "Timbre / Texture", domain: "Art_Aesthetics", weight: 60, opposites: [] },
    { glyph: "🎹", meaning: "Structure / Scale", domain: "Art_Aesthetics", weight: 80, opposites: [] },
    { glyph: "🎤", meaning: "Vocal / Signal", domain: "Art_Aesthetics", weight: 60, opposites: [] },
  ],
  domains: {
    "Emergency_Response": ["💀", "⚠️", "🆘", "🚩", "🚨", "🏥", "🌪️", "⚓", "⏰", "🔇", "💥", "🔄", "🔒"],
    "Wisdom": ["🕯️", "🧘", "⚔️", "🔥", "🧹", "🧭", "💝"],
    "Environmental": ["🌪️", "🌿", "🌍", "💧", "☁️", "🪨", "🛡️", "Re"],
    "Social_Dynamics": ["🦁", "👥", "🗣️", "⚖️", "🚀", "🛑", "💥", "🤝", "🌐", "🔗", "🎯", "🔄"],
    "AI_Tech": ["🎯", "∇J", "PAC"],
    "Time_Temporality": ["⏳", "⌛", "⏰", "⏱️", "⚡", "🌅", "🌇", "🌊"],
    "Uncertainty_Probability": ["🎲", "📊", "🔮", "📈", "📉", "🌀", "E_X"],
    "Consciousness": ["🧠", "🌟", "👥", "🏛️", "💭", "🎭", "➕", "qualia", "⟦·⟧"],
    "Causality": ["➡️", "⚖️", "🔄"],
    "Logic": ["∧", "∨", "¬", "∀", "∃", "⊢", "⊨", "⊥", "⊤", "◇", "□"],
    "Mathematics": ["✔", "≡", "≠", "⊗", "∅", "∞", "📏", "🌐", "🕸️", "📐", "🔼", "∇", "int_mu"],
    "Systems_Theory": ["🎛️", "🔴", "📢", "🧲", "🏗️", "λ", "G_s"],
    "Computer_Science": ["⚓", "🐋", "⛓️", "⚙️", "ZKP", "NP_c"],
    "Info_Theory": ["★", "SNR"],
    "Physics": ["⚡", "🌀", "⚖️", "📏", "⏱️", "🌌", "💎", "🌊", "🔗", "🎯", "⚠️", "🔄", "Λ", "Ω", "H", "γ", "ν", "μ", "τ", "π", "∇", "E_Y", "g_uv"],
    "Chemistry": ["❄️", "🔥", "⚡", "🧬"],
    "Biology": ["🧬", "🌿", "⚡", "🔄", "🧠", "w_fit", "s_sel"],
    "Medicine_Health": ["❤️", "🏥", "EC50", "👢", "IC50"],
    "Economics": ["⚖️", "💎", "📉", "📈", "💰", "🔄", "💡", "🔗", "🛑", "🏆", "🎯", "⚡", "VCG", "U(x)"],
    "Ethics": ["✅", "⚖️", "💝", "stare", "lex"],
    "Cognition": ["◇", "◆", "🧠", "💭", "🔴", "LTP", "intent"],
    "Linguistics": ["λ", "θ", "φ", "Σ", "⟦·⟧"],
    "General_Relativity": ["g", "Γ", "R", "G", "T", "Ric", "g_uv", "Γ_ijk"],
    "Art_Aesthetics": ["🎶", "🎵", "🔁", "🎷", "🎼", "🥁", "💓", "🎹", "🎤", "🎧", "🌈"],
    "Transport_Mobility": ["🛣️", "📍", "🚗", "🏋️"],
    "Set_Theory": ["∅", "∪", "∩", "⊂", "ℵ₀"],
    "Measure_Theory": ["int_mu", "μ_m", "σ-alg"],
    "Complexity_Theory": ["NP_c", "P", "NP"],
    "Comp_Learning": ["PAC", "VC", "ERM"],
    "Decision_Theory": ["EU", "U(x)", "π_pol"],
    "Optimization": ["∇J", "NE", "λ_lag", "KKT"],
    "Game_Theory": ["NE", "VCG", "EU", "BR", "PoA"],
    "Network_Theory": ["🌐", "⇄", "R₀", "k_deg", "C_clus"],
    "Control_Theory": ["G_s", "u(t)", "y(t)"],
    "Dynamical_Systems": ["λ", "ẋ", "φ_flow", "x*"],
    "Stochastic": ["ẋ", "E_X", "W_t", "M_t"],
    "Signal_Processing": ["SNR", "FFT", "H(z)"],
    "Cryptography": ["ZKP", "Enc", "Dec"],
    "Materials_Science": ["E_Y", "σ_str", "ε_str"],
    "Fluid_Dynamics": ["Re", "Ma", "St"],
    "Evolutionary_Biology": ["w_fit", "s_sel", "μ_mut"],
    "Neuroscience": ["LTP", "fMRI"],
    "Pharmacology": ["EC50", "IC50"],
    "Epidemiology": ["R₀", "ATE", "SIR"],
    "Ecology": ["⇄", "K_cap"],
    "Philosophy_of_Mind": ["qualia", "intent"],
    "Social_Choice": ["VCG", "Borda"],
    "Law": ["stare", "lex"],
    "Footwear": ["👟", "👢", "sole"],
    "Sports_Equipment": ["👟", "🏋️", "ball"],
    "Clothing_Textiles": ["🧵", "💎", "weave"],
    "Color_Spectrum": ["🧵", "🔴", "🌈", "hue"],
    "Causal_Inference": ["do(·)", "ATE", "DAG"],
    "Political_Science": ["VCG", "demos"],
    "Diff_Geometry": ["Ric", "g_uv", "Γ_ijk"],
  },
  compass: {
    "North": { name: "Eternal Stability", symbols: ["🐋", "🌿", "⚓"], mod97: 28 },
    "East": { name: "Sovereign Protocol", symbols: ["🦁", "🐋", "⚓"], mod97: 17 },
    "South": { name: "Grounded Constraint", symbols: ["⚓", "⛓️"], mod97: 32 },
    "West": { name: "Brave Insight", symbols: ["💀", "🕯️", "🐋", "🦁"], mod97: 48 },
    "Center": { name: "Universal Equilibrium", symbols: ["🌪️", "🐋", "🌿", "🦁", "🎯"], mod97: 48 },
    "Zenith": { name: "Transcendent Clarity", symbols: ["🔥", "🧹", "🧭"], mod97: 84 },
    "Nadir": { name: "Instant Awareness", symbols: ["⚡", "🧘"], mod97: 93 },
  },
  cross_domain_bridges: [
    // V8.2 primary flow
    { from: "Environmental",      to: "Social_Dynamics",    symbol: "🌿",    function: "Sustainability_to_Community" },
    { from: "Social_Dynamics",    to: "AI_Tech",            symbol: "🐋",    function: "Narrative_to_Prediction" },
    { from: "AI_Tech",            to: "Emergency_Response", symbol: "🎯",    function: "Prediction_to_Response" },
    { from: "AI_Tech",            to: "Wisdom",             symbol: "🐋",    function: "Prediction_to_Insight" },
    { from: "Emergency_Response", to: "Wisdom",             symbol: "💀",    function: "Crisis_to_Insight" },
    // Formal science chain
    { from: "Time_Temporality",   to: "Causality",          symbol: "➡️",   function: "Temporal_Precedence" },
    { from: "Causality",          to: "Causal_Inference",   symbol: "do(·)", function: "Correlation_to_Intervention" },
    { from: "Logic",              to: "Mathematics",         symbol: "⊢",    function: "Proof_to_Structure" },
    { from: "Mathematics",        to: "Set_Theory",          symbol: "∅",    function: "Structure_to_Collection" },
    { from: "Mathematics",        to: "Physics",             symbol: "∇",    function: "Gradient_Field" },
    { from: "Physics",            to: "Chemistry",           symbol: "⚡",   function: "Energy_to_Reaction" },
    { from: "Chemistry",          to: "Biology",             symbol: "🧬",   function: "Molecule_to_Life" },
    { from: "Biology",            to: "Cognition",           symbol: "🧠",   function: "Neural_to_Mind" },
    { from: "Cognition",          to: "Consciousness",       symbol: "💭",   function: "Process_to_Awareness" },
    { from: "Consciousness",      to: "Ethics",              symbol: "⚖️",   function: "Awareness_to_Values" },
    { from: "Ethics",             to: "Wisdom",              symbol: "💝",   function: "Values_to_Integration" },
    // Applied world bridges
    { from: "Clothing_Textiles",  to: "Color_Spectrum",      symbol: "🧵",   function: "Garment_Pigmentation" },
    { from: "Clothing_Textiles",  to: "Economics",           symbol: "💎",   function: "Textile_Market_Value" },
    { from: "Color_Spectrum",     to: "Cognition",           symbol: "🔴",   function: "Chromatic_Attention_Capture" },
    { from: "Transport_Mobility", to: "Environmental",       symbol: "🚗",   function: "Mobility_Carbon_Footprint" },
    { from: "Footwear",           to: "Sports_Equipment",    symbol: "👟",   function: "Athletic_Shoe_to_Sport" },
    { from: "Footwear",           to: "Medicine_Health",     symbol: "👢",   function: "Industrial_Boot_to_Safety" },
    { from: "Sports_Equipment",   to: "Transport_Mobility",  symbol: "🏋️",  function: "Equipment_Inventory_Logistics" },
    { from: "Color_Spectrum",     to: "Art_Aesthetics",      symbol: "🌈",   function: "Colour_Composition" },
    // V9 new domain bridges
    { from: "Dynamical_Systems",  to: "Systems_Theory",      symbol: "λ",    function: "Eigenvalue_Stability" },
    { from: "Dynamical_Systems",  to: "Stochastic",          symbol: "ẋ",    function: "Deterministic_to_Random" },
    { from: "Network_Theory",     to: "Social_Dynamics",     symbol: "🌐",   function: "Graph_to_Community" },
    { from: "Network_Theory",     to: "Ecology",             symbol: "⇄",    function: "Topology_to_Ecosystem" },
    { from: "Optimization",       to: "AI_Tech",             symbol: "∇J",   function: "Loss_Gradient_Training" },
    { from: "Optimization",       to: "Game_Theory",         symbol: "NE",   function: "Optimum_to_Equilibrium" },
    { from: "Game_Theory",        to: "Economics",           symbol: "VCG",  function: "Strategy_to_Mechanism" },
    { from: "Neuroscience",       to: "Cognition",           symbol: "LTP",  function: "Plasticity_to_Learning" },
    { from: "Signal_Processing",  to: "Info_Theory",         symbol: "SNR",  function: "Noise_to_Entropy" },
    { from: "Control_Theory",     to: "Systems_Theory",      symbol: "G_s",  function: "Feedback_Control" },
    { from: "Cryptography",       to: "Computer_Science",    symbol: "ZKP",  function: "Proof_to_Security" },
    { from: "Stochastic",         to: "Uncertainty_Probability", symbol: "E_X", function: "Process_to_Distribution" },
    { from: "Evolutionary_Biology",to: "Biology",            symbol: "w_fit",function: "Fitness_to_Adaptation" },
    { from: "Measure_Theory",     to: "Mathematics",         symbol: "int_mu",function: "Lebesgue_to_Structure" },
    { from: "Diff_Geometry",      to: "General_Relativity",  symbol: "Ric",  function: "Curvature_to_Spacetime" },
    { from: "Complexity_Theory",  to: "Computer_Science",    symbol: "NP_c", function: "Hardness_to_Algorithm" },
    { from: "Comp_Learning",      to: "AI_Tech",             symbol: "PAC",  function: "Learnability_to_Model" },
    { from: "Epidemiology",       to: "Network_Theory",      symbol: "R₀",   function: "Contagion_to_Spread" },
    { from: "Pharmacology",       to: "Medicine_Health",     symbol: "EC50", function: "Dose_to_Outcome" },
    { from: "Philosophy_of_Mind", to: "Consciousness",       symbol: "qualia",function: "Phenomenology_to_Awareness" },
    { from: "Causal_Inference",   to: "Epidemiology",        symbol: "ATE",  function: "Effect_to_Population" },
    { from: "Decision_Theory",    to: "Game_Theory",         symbol: "EU",   function: "Individual_to_Strategic" },
    { from: "Social_Choice",      to: "Political_Science",   symbol: "VCG",  function: "Mechanism_to_Policy" },
    { from: "Law",                to: "Ethics",              symbol: "stare",function: "Precedent_to_Principle" },
    { from: "Linguistics",        to: "Consciousness",       symbol: "⟦·⟧",  function: "Meaning_to_Awareness" },
    { from: "Materials_Science",  to: "Physics",             symbol: "E_Y",  function: "Material_to_Force" },
    { from: "Fluid_Dynamics",     to: "Environmental",       symbol: "Re",   function: "Flow_to_Climate" },
  ],
};
