import type { JsonSchema } from "./json-schema-types";

const finiteNumberSchema = (): JsonSchema => ({ type: "number" });
const nonNegativeIntegerSchema = (): JsonSchema => ({ type: "integer", minimum: 0 });
const positiveIntegerSchema = (): JsonSchema => ({ type: "integer", exclusiveMinimum: 0 });
const stringOrNumberSchema = (): JsonSchema => ({ anyOf: [{ type: "string" }, { type: "number" }] });
const stringArraySchema = (): JsonSchema => ({ type: "array", items: { type: "string" } });

export const compassRunRecordSchema: JsonSchema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://blue-whale.app/schemas/compass-run-v1.json",
  title: "CompassRunRecord",
  type: "object",
  additionalProperties: false,
  required: [
    "metadata",
    "parameters",
    "initialState",
    "metrics",
    "structuralSummary",
    "eventLog",
  ],
  properties: {
    metadata: {
      type: "object",
      additionalProperties: false,
      required: [
        "schemaVersion",
        "parameterLexiconVersion",
        "metricsLexiconVersion",
        "runId",
        "timestamp",
        "engineVersion",
        "seed",
      ],
      properties: {
        schemaVersion: { enum: ["compass-run-v1", "compass-run-v1.1"] },
        parameterLexiconVersion: { const: "compass-v1" },
        metricsLexiconVersion: { const: "compass-v1" },
        runId: { type: "string", minLength: 1 },
        timestamp: { type: "string", format: "date-time" },
        engineVersion: { type: "string", minLength: 1 },
        ontologyVersion: { type: "string" },
        seed: stringOrNumberSchema(),
        mode: { type: "string" },
        provider: { type: "string" },
        model: { type: "string" },
      },
    },
    probe: {
      type: "object",
      additionalProperties: false,
      properties: {
        probeId: { type: "string" },
        probeFamily: { type: "string" },
        probeRole: { type: "string" },
        probeVersion: { type: "string" },
        sourceTextHash: { type: "string" },
        sourceTextTitle: { type: "string" },
        sourceTextPreview: { type: "string" },
      },
    },
    parameters: {
      type: "object",
      additionalProperties: false,
      required: [
        "alpha",
        "gamma",
        "delta",
        "beta",
        "lambda",
        "eta",
        "epsilon",
        "temperature",
        "seed",
        "threshold",
        "maxSequenceLength",
        "maxSteps",
        "architectureMode",
      ],
      properties: {
        alpha: finiteNumberSchema(),
        gamma: finiteNumberSchema(),
        delta: finiteNumberSchema(),
        beta: finiteNumberSchema(),
        lambda: finiteNumberSchema(),
        eta: finiteNumberSchema(),
        epsilon: finiteNumberSchema(),
        temperature: finiteNumberSchema(),
        seed: stringOrNumberSchema(),
        threshold: finiteNumberSchema(),
        maxSequenceLength: positiveIntegerSchema(),
        maxSteps: positiveIntegerSchema(),
        architectureMode: { type: "string", minLength: 1 },
      },
    },
    parameterProfiles: {
      type: "object",
      additionalProperties: false,
      properties: {
        evaluationProfile: { type: "string" },
        relationalProfile: { type: "string" },
        searchProfile: { type: "string" },
        thresholdProfile: { type: "string" },
        constraintProfile: { type: "string" },
      },
    },
    initialState: {
      type: "object",
      additionalProperties: false,
      required: ["initialSequence", "initialLength"],
      properties: {
        initialSequence: stringArraySchema(),
        initialLength: nonNegativeIntegerSchema(),
        initialNarrative: { type: "string" },
        distilledNarrative: { type: "string" },
        initialMetrics: {
          type: "object",
          additionalProperties: false,
          properties: {
            telic_score: finiteNumberSchema(),
            resilience: finiteNumberSchema(),
            telic_curvature: finiteNumberSchema(),
            path_integral: finiteNumberSchema(),
            mod97_value: stringOrNumberSchema(),
            compass_orientation: { type: "string" },
            consensus_score: finiteNumberSchema(),
            adversarial_status: { enum: ["passed", "failed", "unknown"] },
          },
        },
      },
    },
    metrics: {
      type: "object",
      additionalProperties: false,
      required: [
        "telic_score",
        "resilience",
        "telic_curvature",
        "path_integral",
        "mod97_value",
        "compass_orientation",
        "consensus_score",
        "adversarial_status",
      ],
      properties: {
        telic_score: finiteNumberSchema(),
        resilience: finiteNumberSchema(),
        telic_curvature: finiteNumberSchema(),
        path_integral: finiteNumberSchema(),
        mod97_value: stringOrNumberSchema(),
        compass_orientation: { type: "string" },
        consensus_score: finiteNumberSchema(),
        adversarial_status: { enum: ["passed", "failed", "unknown"] },
      },
    },
    runSummary: {
      type: "object",
      additionalProperties: false,
      properties: {
        best_telic_score: finiteNumberSchema(),
        best_score_step: nonNegativeIntegerSchema(),
        plateau_start_step: nonNegativeIntegerSchema(),
        growth_phase_end_step: nonNegativeIntegerSchema(),
        mean_resilience: finiteNumberSchema(),
        peak_telic_curvature: finiteNumberSchema(),
        final_compass_orientation: { type: "string" },
        adversarial_passed: { type: "boolean" },
      },
    },
    structuralSummary: {
      type: "object",
      additionalProperties: false,
      required: ["finalSequence", "finalLength"],
      properties: {
        finalSequence: stringArraySchema(),
        finalLength: nonNegativeIntegerSchema(),
        convergenceIters: nonNegativeIntegerSchema(),
        contractionRate: finiteNumberSchema(),
        fidelity: finiteNumberSchema(),
        cfIndex: finiteNumberSchema(),
        mod97Final: stringOrNumberSchema(),
        bestScoreStep: nonNegativeIntegerSchema(),
        plateauStartStep: nonNegativeIntegerSchema(),
        lastInventoryChangeStep: nonNegativeIntegerSchema(),
        lastOrderChangeStep: nonNegativeIntegerSchema(),
        lastAcceptedChangeStep: nonNegativeIntegerSchema(),
        lastMeaningfulAcceptedStep: nonNegativeIntegerSchema(),
        meaningfulChangeCount: nonNegativeIntegerSchema(),
        nullOrNoEffectStepCount: nonNegativeIntegerSchema(),
        stabilityRatio: finiteNumberSchema(),
        bridgeEventCount: nonNegativeIntegerSchema(),
        uniqueBridgeCount: nonNegativeIntegerSchema(),
        observerEmerged: { type: "boolean" },
        observerStep: nonNegativeIntegerSchema(),
      },
    },
    eventLog: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["type", "step"],
        properties: {
          type: {
            enum: [
              "new_best",
              "inventory_change",
              "order_change",
              "meaningful_order_change",
              "plateau_start",
              "sequence_stabilized",
              "bridge_event",
              "observer_candidate",
              "observer_emerged",
              "structural_warning",
              "collapse_warning",
              "adversarial_failure",
            ],
          },
          step: nonNegativeIntegerSchema(),
          score: finiteNumberSchema(),
          sequence: stringArraySchema(),
          payload: {
            type: "object",
            additionalProperties: true,
          },
        },
      },
    },
    debugTrace: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["step", "sequence", "proposalType", "accepted", "metrics"],
        properties: {
          step: nonNegativeIntegerSchema(),
          sequence: stringArraySchema(),
          proposalType: { enum: ["init", "none", "insert", "delete", "swap", "combine"] },
          accepted: { anyOf: [{ type: "boolean" }, { type: "null" }] },
          deltaScore: finiteNumberSchema(),
          inventoryChanged: { type: "boolean" },
          orderChanged: { type: "boolean" },
          delta: {
            anyOf: [
              {
                type: "object",
                additionalProperties: false,
                required: ["kind"],
                properties: { kind: { const: "none" } },
              },
              {
                type: "object",
                additionalProperties: false,
                required: ["kind", "symbol"],
                properties: {
                  kind: { const: "insert" },
                  symbol: { type: "string" },
                  index: nonNegativeIntegerSchema(),
                },
              },
              {
                type: "object",
                additionalProperties: false,
                required: ["kind", "symbol"],
                properties: {
                  kind: { const: "delete" },
                  symbol: { type: "string" },
                  index: nonNegativeIntegerSchema(),
                },
              },
              {
                type: "object",
                additionalProperties: false,
                required: ["kind", "fromIndex", "toIndex"],
                properties: {
                  kind: { const: "swap" },
                  fromIndex: nonNegativeIntegerSchema(),
                  toIndex: nonNegativeIntegerSchema(),
                },
              },
              {
                type: "object",
                additionalProperties: false,
                required: ["kind", "symbols"],
                properties: {
                  kind: { const: "combine" },
                  symbols: stringArraySchema(),
                  result: { type: "string" },
                },
              },
            ],
          },
          metrics: {
            type: "object",
            additionalProperties: false,
            properties: {
              telic_score: finiteNumberSchema(),
              resilience: finiteNumberSchema(),
              telic_curvature: finiteNumberSchema(),
              path_integral: finiteNumberSchema(),
              mod97_value: stringOrNumberSchema(),
              compass_orientation: { type: "string" },
              consensus_score: finiteNumberSchema(),
              adversarial_status: { enum: ["passed", "failed", "unknown"] },
            },
          },
          rawDuality: finiteNumberSchema(),
          duality: finiteNumberSchema(),
          bridgeActive: { type: "boolean" },
          bridgeType: { type: "string" },
          observerCandidate: { type: "boolean" },
          observerEmerged: { type: "boolean" },
          notes: { type: "string" },
        },
      },
    },
    adversarial: {
      type: "object",
      additionalProperties: false,
      properties: {
        adversarialTestName: { type: "string" },
        adversarialTestVersion: { type: "string" },
        adversarialFailureReason: { type: "string" },
      },
    },
    tags: stringArraySchema(),
  },
};
